# Generated by Django 4.0.1 on 2022-02-07 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='blogimage')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.TextField()),
            ],
        ),
    ]
